### PR TITLE
fix batchSize args

### PR DESCRIPTION
**Pull request by zwq000**
Batchsize does not work, causing an error when importing hset data
The batchsize parameter given when the program starts does not work

### CODE REVIEW

**Comment by yannh** [comment]
Thanks for the notice! Indeed :facepalm:  I d rather not rely on a global variable, but I ll get back to this soon, thanks for the report :+1:

**Comment by yannh** [comment]
Fixed in https://github.com/yannh/redis-dump-go/pull/23

**Comment by yannh** [comment]
Released v0.5.1 :+1:

**Comment by zwq000** [comment]
It looks like there are too many arguments of a function, but okay

**Pull request closed without merging**
